#ifndef TEMPLATER_H
#define TEMPLATER_H

/* @Todo: Instead, get these from files.. easier. */

char *g_template_source =
"#define SUB_CONSOLE\n"
"#include \"chihab.h\"\n"
"#include \"cm_io.c\"\n"
"\n"
"ENTRY\n"
"{\n"
"  printf(\"Hello world\\n\");\n"
"  RETURN_FROM_MAIN(EXIT_SUCCESS);\n"
"}";

char *g_template_build = 
"@echo off\n"
"setlocal\n"
"cd /D \"%%~dp0\"\n"
"\n"
"set HOME=%%HOMEDRIVE%%\\%%HOMEPATH%%\n"
"\n"
"if exist C:\\vc_env\\msvc\\setup.bat ( @call \"C:\\vc_env\\msvc\\setup.bat\")\n"
"\n"
"where /q cl || (\n"
"  echo ERROR: \"cl\" not found - please run from MSVC x64 native tools command prompt.\n"
"  exit /b 1\n"
")\n"
"\n"
"rem -- Get command-line arguments -----------------------------------------------------\n"
"for %%%%a in (%%*) do set \"%%%%a=1\"\n"
"if not \"%%msvc%%\"==\"1\" if not \"%%clang%%\"==\"1\" set msvc=1\n"
"if not \"%%debug%%\"==\"1\" set release=1\n"
"if \"%%debug%%\"==\"1\"   set release=0 && echo [debug mode]\n"
"if \"%%release%%\"==\"1\" set debug=0 && echo [release mode]\n"
"if \"%%msvc%%\"==\"1\"    set clang=0 && echo [msvc compile]\n"
"if \"%%clang%%\"==\"1\"   set msvc=0 && echo [clang compile]\n"
"\n"
"rem -- CRT_NO_CRT ----------------------------------------------------------------------\n"
"set crt=0\n"
"if not \"%%crt%%\"==\"1\" (\n"
"  echo [NO_CRT LINKED]\n"
"  set def_crt=/DNO_CRT_LINKED\n"
"  set cc_nocrt=/Zl /Gs9999999\n"
"  set l_nocrt=/STACK:0x100000,0x100000\n"
"  set crt_libs=vcruntime.lib ucrt.lib\n"
")\n"
"if \"%%crt%%\"==\"1\" (\n"
"  set def_crt=/DCRT_LINKED\n"
"  set cc_asan=/fsanitize=address\n"
"  set cc_asan=\n"
"  set cc_nocrt=\n"
"  set l_nocrt=\n"
")\n"
"\n"
"rem -- Common options -----------------------------------------------------------------\n"
"set src_dir=src\n"
"set program=%s\n"
"set source=%s\n"
"set bin=bin\n"
"set ext=.%s\n"
"set out_path=%%bin%%\\%%program%%\n"
"set out_path_debug=%%bin%%\\%%program%%_debug\n"
"\n"
"set def_dll=\n"
"set lk_dll=\n"
"\n"
"if \"%%ext%%\"==\".dll\" (\n"
"  set def_dll=/DCM_DLL\n"
"  set lk_dll=/DLL\n"
")\n"
"\n"
"rem -- Resource options ---------------------------------------------------------------\n"
"set assets=assets\n"
"set rc_res=%%bin%%\\resource.res\n"
"set rsc_out=/fo %%rc_res%%\n"
"set rc_file=%%assets%%\\resource.rc\n"
"set rc_includes=/i %%src_dir%%\\\n"
"set rc=rc.exe /NOLOGO\n"
"\n"
"rem -- Scaffolding ---------------------------------------------------------------------\n"
"if not exist %%bin%% md %%bin%%\n"
"if exist %%out_path%%.* del %%out_path%%.*\n"
"if exist %%out_path_debug%%.* del %%out_path_debug%%.*\n"
"if exist assets if not exist %%rc_res%% %%rc%% %%rc_includes%% %%rsc_out%% %%rc_file%%\n"
"\n"
"rem -- MSVC compiler options ----------------------------------------------------------\n"
"set no_cpp_options=/EHsc /EHa- /GR-\n"
"set cc_secure=/GS- /guard:cf-\n"
"set cc_options=/options:strict %%no_cpp_options%% %%cc_secure%% /FC /c /Tc \n"
"set cc_diag=/diagnostics:caret\n"
"\n"
"set cc=cl /nologo %%cc_diag%% %%cc_options%%\n"
"set cc_includes=/I%%src_dir%% /Ichihab\n"
"set cc_def=%%cc_def%% %%def_crt%% %%def_dll%%\n"
"\n"
"rem -- (4090)const/volatile (4189)var init unused (5045)spectre mitigation -------------\n"
"set cc_w=/wd4090 /wd4189 /wd5045 /wd4047 /wd4133 /wd4024 /wd4022 /wd4113\n"
"set cc_std=/experimental:c11atomics /std:clatest\n"
"set cc_opti=/Os /Oi\n"
"set cc_dbg=/Zi\n"
"\n"
"rem -- Normal build --------------------------------------------------------------------\n"
"set cc_pdb_out=/Fd:%%out_path%%.pdb\n"
"set cc_obj=%%out_path%%.obj\n"
"set cc_out=/Fo:%%cc_obj%% %%cc_pdb_out%%\n"
"\n"
"rem -- Debug build ---------------------------------------------------------------------\n"
"set cc_pdb_out_debug=/Fd:%%out_path_debug%%.pdb\n"
"set cc_obj_debug=%%out_path_debug%%.obj\n"
"set cc_out_debug=/Fo:%%cc_obj_debug%% %%cc_pdb_out_debug%%\n"
"\n"
"set cc_flags=%%cc_w%% %%cc_def%% %%cc_dbg%% %%cc_nocrt%% %%cc_std%% %%cc_opti%% %%cc_includes%% %%cc_asan%%\n"
"\n"
"rem -- MSVC linker options ------------------------------------------------------------\n"
"set linker=link /NOLOGO /INCREMENTAL:NO %%lk_dll%%\n"
"set l_debug=/DEBUG:FULL /DYNAMICBASE:NO\n"
"set l_sys=/PROFILE /GUARD:NO\n"
"set l_opt=/OPT:ICF /OPT:REF\n"
"set l_arch=/MACHINE:X64 \n"
"set l_options=/WX %%l_arch%% %%l_nocrt%% %%l_sys%%\n"
"\n"
"set l_files=/ILK:%%out_path%%.ilk /MAP:%%out_path%%.map /PDB:%%out_path%%.pdb \n"
"set l_files_debug=/ILK:%%out_path_debug%%.ilk /MAP:%%out_path_debug%%.map /PDB:%%out_path_debug%%.pdb \n"
"\n"
"rem -- Libraries ----------------------------------------------------------------------\n"
"rem set d3d12libs=d3dcompiler.lib D3D12.lib dxgi.lib dxguid.lib dwmapi.lib \n"
"set win_libs=uuid.lib Shlwapi.lib Ole32.lib Kernel32.lib User32.lib Gdi32.lib Credui.lib\n"
"set libs=%%win_libs%% %%c_libs%% %%d3d12libs%% %%crt_libs%% %%weblibs%%\n"
"\n"
"set l_all=%%l_debug%% %%l_options%% %%libs%% %%l_delay%% %%l_opti%%\n"
"set l_out=/OUT:%%out_path%%%%ext%%\n"
"set l_out_debug=/OUT:%%out_path_debug%%%%ext%%\n"
"\n"
"rem -- NORMAL BUILD -------------------------------------------------------------------\n"
"if \"%%release%%\"==\"1\" (\n"
"  set compiling=%%cc%% %%src_dir%%\\%%source%%.c %%cc_flags%% %%cc_out%%\n"
"  set linking=%%linker%% %%cc_obj%% %%bin%%\\*.res %%l_files%% %%l_out%% %%l_all%%\n"
")\n"
"\n"
"if \"%%debug%%\"==\"1\" (\n"
"  set compiling=%%cc%% %%src_dir%%\\%%source%%.c /DDEBUG %%cc_flags%% %%cc_out_debug%%\n"
"  set linking=%%linker%% %%cc_obj_debug%% %%bin%%\\*.res %%l_files_debug%% %%l_out_debug%% %%l_all%%\n"
")\n"
"\n"
"echo %%compiling%%\n"
"%%compiling%% || exit /b 1\n"
"\n"
"echo:\n"
"echo %%linking%%\n"
"%%linking%%   || exit /b 1\n"
"\n"
"rem -- Launch it ----------------------------------------------------------------------\n"
"rem longsure raddbg --auto-run\n"
"\n"
"rem -- Misc ---------------------------------------------------------------------------\n"
"ctags -f tags --langmap=c:.c.h --languages=c -R src\n";

#endif // TEMPLATER_H
